import React, { useState } from 'react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import './ViewStyles.css';

const DEMO_SIGNALS = [
  { id: 1, symbol: 'BTC/USD', signal: 'BUY', entry: 67200, stopLoss: 65800, takeProfit: 70500, confidence: 92, timeframe: '4H' },
  { id: 2, symbol: 'ETH/USD', signal: 'SELL', entry: 3450, stopLoss: 3580, takeProfit: 3150, confidence: 85, timeframe: '1H' },
  { id: 3, symbol: 'XAU/USD', signal: 'BUY', entry: 2315, stopLoss: 2295, takeProfit: 2360, confidence: 78, timeframe: '1D' },
  { id: 4, symbol: 'EUR/USD', signal: 'SELL', entry: 1.0845, stopLoss: 1.0895, takeProfit: 1.0745, confidence: 81, timeframe: '4H' },
];

export default function AISignalsView() {
  const [signals] = useState(DEMO_SIGNALS);
  const [executingId, setExecutingId] = useState(null);

  const handleExecuteTrade = async (signal) => {
    try {
      setExecutingId(signal.id);

      const signalData = {
        pair: signal.symbol,
        type: signal.signal.toLowerCase(),
        confidence: signal.confidence,
        entryPrice: signal.entry,
        stopLoss: signal.stopLoss,
        takeProfit: signal.takeProfit,
        quantity: 0.01,
        candleTime: new Date().toISOString(),
      };

      const response = await fetch('/hcgi/api/ai-signals/execute', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${pb.authStore.token}`,
        },
        body: JSON.stringify({ signal: signalData }),
      });

      const data = await response.json();

      if (data.success) {
        toast.success(`${signal.signal} order placed for ${signal.symbol}`);
      } else {
        toast.error(data.message || 'Order rejected');
      }
    } catch (error) {
      console.error('Execute trade error:', error);
      toast.error(error.message || 'Failed to execute trade');
    } finally {
      setExecutingId(null);
    }
  };

  return (
    <div className="view-container">
      <div className="view-header">
        <h1>AI Signals</h1>
        <p>Active trade signals generated by Oracle AI — updated in real-time</p>
      </div>

      <div className="signals-grid">
        {signals.map((signal) => (
          <div key={signal.id} className="signal-card">
            <div className="signal-header">
              <h3>{signal.symbol}</h3>
              <span className={`signal-badge ${signal.signal.toLowerCase()}`}>{signal.signal}</span>
            </div>

            <div className="signal-details">
              <div className="detail-row">
                <span className="label">Timeframe</span>
                <span className="value">{signal.timeframe}</span>
              </div>
              <div className="detail-row">
                <span className="label">Entry Price</span>
                <span className="value">{signal.entry.toLocaleString()}</span>
              </div>
              <div className="detail-row">
                <span className="label">Stop Loss</span>
                <span className="value" style={{ color: '#ef4444' }}>{signal.stopLoss.toLocaleString()}</span>
              </div>
              <div className="detail-row">
                <span className="label">Take Profit</span>
                <span className="value" style={{ color: '#10b981' }}>{signal.takeProfit.toLocaleString()}</span>
              </div>
              <div className="detail-row">
                <span className="label">Confidence</span>
                <span className="value">{signal.confidence}%</span>
              </div>
            </div>

            <div className="confidence-bar">
              <div className="confidence-fill" style={{ width: `${signal.confidence}%` }} />
            </div>

            <button
              className="btn-execute"
              onClick={() => handleExecuteTrade(signal)}
              disabled={executingId === signal.id}
            >
              {executingId === signal.id ? 'Executing...' : 'Execute Trade'}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
